### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by robynmaya** [srob12/prj-rev-bwfs-dasmoto#4]
Grade : Needs Improvement 

My recommendation to you : 

1. Include Meta tags in your `<head></head>` element

2. Encapsulate a section using `<div></div>` and you may also try exploring HTML5 Semantic Elements (which for certain things, can be used in place of `<div></div>`). 

For certain types of websites, it always appropriate to structure them using HTML5 semantic elements, such as Blogs, Company/Organization Website, Static Website. [Read More](https://codepen.io/mi-lee/post/an-overview-of-html5-semantics).

3. Always indent your code properly, use [this](https://www.10bestdesign.com/dirtymarkup/) to help you auto-indent your HTML and CSS pages.

**Comment by srob12** [comment]
Thank you for the feedback. Is there anything else that I need to do to move on with the course? I just want to be sure that I don't need to do something over again and re-submit?

Thanks again for the valuable tips!

~Steven

**Comment by robynmaya** [comment]
If you followed the recommendation, you should be good to move forward to the next project in the course :)
